from django.core.management.base import BaseCommand
from accounts.models import Disciplina

class Command(BaseCommand):
    help = 'Importa lista de disciplinas para o banco de dados'

    def handle(self, *args, **kwargs):
        disciplinas = [
            "Acessibilidade e Lazer",
            "Administração de Recursos Humanos",
            "Agente Cultural",
            "Agricultura Urbana",
            "Agroecologia em Territórios Rural e Urbano",
            "Agroindustrialização e processamento de alimentos orgânicos",
            "Álgebra Linear",
            "Algoritmos",
            "Algoritmos e Programação",
            "Análise e Projeto de Sistemas",
            "Análise Estratégica",
            "Análise Estratégica, Macro e Micro Organizacional",
            "Aprendizagem autônoma e ambiente virtual de ensino e aprendizagem",
            "Arquitetura e Organização de Computadores",
            "Arranjos Produtivos Locais",
            "Arte e Cultura Aplicada ao Turismo Nacional e América do Sul",
            "Arte e Cultura Aplicada ao Turismo Regional",
            "Arte, Cultura e Lazer",
            "Artes",
            "Artes I",
            "Artes II",
            "Artes Visuais",
            "Atividades Recreativas e de Lazer",
            "Automação Industrial",
            "Avaliação: desafios e perspectivas",
            "Banco de Dados",
            "Banco de Dados I",
            "Banco de Dados II",
            "Big Data & Cloud Computing - Optativa",
            "Biologia",
            "Biologia dos Organismos",
            "Biologia I",
            "Biologia II",
            "Biologia III",
            "Biologia vegetal aplicada",
            "Cabeamento Estruturado",
            "Cálculo I",
            "Cálculo II",
            "Cálculo III",
            "Cálculo Numérico",
            "Cartografia temática digital",
            "Ciências da Natureza e suas Tecnologias",
            "Ciências Humanas e suas Tecnologias",
            "Circuitos Elétricos I",
            "Circuitos Elétricos II",
            "Circuitos Elétricos III",
            "Clássicos: estudos dirigidos",
            "Comportamento e Aprendizagem Organizacional",
            "Comportamento Organizacional",
            "Computação em Nuvem",
            "Comunicação e Expressão Aplicadas à Agroecologia",
            "Comunicação e Expressão I",
            "Controle Digital",
            "Corpo, Lazer e Sociedade",
            "Cultivo de hortaliças",
            "Culturas Regionais",
            "Curso FIC - Monitor de Atividades de Lazer/Recreação",
            "Curso FIC - Operador de Computador",
            "Desenho Técnico",
            "Desenvolvimento de Sistemas I",
            "Desenvolvimento de Sistemas II",
            "Desenvolvimento de Sistemas para Web",
            "Desenvolvimento e Aprendizagem",
            "Desenvolvimento e Sustentabilidade de Sistemas Agroalimentares",
            "Desenvolvimento Interpessoal",
            "Desenvolvimento Interpessoal I",
            "Desenvolvimento Interpessoal II",
            "Desenvolvimento Interpessoal III",
            "Desenvolvimento para Dispositivos Móveis",
            "Desenvolvimento Web",
            "Didática: teorias e práticas",
            "Dispositivos Lógicos Programáveis",
            "Ecologia",
            "Economia solidária",
            "Educação Física",
            "Educação e Trabalho",
            "Educação Física e Lazer",
            "Educação popular",
            "Eletrônica Analógica I",
            "Eletrônica Analógica II",
            "Eletrônica Analógica III",
            "Eletrônica de Potência",
            "Eletrônica Digital I",
            "Eletrônica Digital II",
            "Eletrônica Industrial",
            "Empreendedorismo",
            "Engenharia de Software",
            "Espanhol",
            "Espanhol I",
            "Esportes Coletivos",
            "Esportes Individuais",
            "Estágio Curricular",
            "Estágio Supervisionado",
            "Estatística Descritiva",
            "Estratégia e Gestão de Projetos",
            "Estruturas de Dados",
            "Ética",
            "Extensão I - Conceitos da Extensão",
            "Filosofia",
            "Filosofia da Educação",
            "Física",
            "Física Aplicada I",
            "Física Aplicada II",
            "Física Aplicada III",
            "Física I",
            "Física II",
            "Fruticultura",
            "Fundamentos da Computação",
            "Fundamentos da Gestão",
            "Fundamentos da Linguística",
            "Fundamentos de Estatística Aplicada",
            "Fundamentos do Esporte",
            "Fundamentos do Lazer",
            "Fundamentos do Solo nos Agroecossistemas",
            "Fundamentos do Turismo",
            "Geografia",
            "Geografia Aplicada ao Turismo Nacional e América do Sul",
            "Geografia e Agroecologia",
            "Geografia I",
            "Geografia II",
            "Geografia III",
            "Geografia, Natureza e Lazer",
            "Gerenciamento e Segurança de Redes",
            "Gestão da Produção",
            "Gestão da Qualidade e Responsabilidade Social",
            "Gestão de Cadeia de Suprimento",
            "Gestão de Eventos",
            "Gestão de Marketing",
            "Gestão de Pessoas",
            "Gestão de Processos e Serviços",
            "Gestão de Serviços e Operações",
            "Gestão e Empreendedorismo",
            "Gestão Estratégica e Financeira",
            "Gestão Financeira",
            "Gestão Socioambiental e da Qualidade",
            "Hardware e Manutenção de Computadores",
            "Higiene e Segurança do Trabalho",
            "História",
            "História Aplicada ao Turismo Nacional e América do Sul",
            "História Aplicada ao Turismo Regional",
            "História da Arte",
            "História da Educação",
            "História I",
            "História II",
            "História III",
            "Informática Aplicada à Pesquisa Turística",
            "Informática Básica",
            "Informática Instrumental",
            "Informática para Gestão e Negócios",
            "Inglês",
            "Inglês aplicado à eletrônica",
            "Inglês aplicado à Informação",
            "Inglês Aplicado ao Lazer",
            "Inglês Instrumental - Optativa",
            "Instalação e Configuração de Serviços de Redes",
            "Instrumentação e Condicionamento de Sinais",
            "Inteligência Artificial - Optativa",
            "Interface Humano-Computador",
            "Interfaces Web",
            "Introdução à Agroecologia em Territórios Rural e Urbano",
            "Introdução a Banco de Dados",
            "Introdução a Engenharia de Software",
            "Introdução à Gestão de Projetos",
            "Introdução aos Estudos Literários",
            "Língua Portuguesa e Literatura",
            "Lazer e Artes Visuais",
            "Lazer e Cultura Digital",
            "Lazer e Música",
            "Leitura Crítica da Gramática",
            "Leitura e Produção Textual",
            "LIBRAS",
            "Língua Espanhola I",
            "Língua Espanhola II",
            "Língua Espanhola III",
            "Língua Espanhola IV",
            "Língua Espanhola V",
            "Língua Estrangeira - Espanhol",
            "Língua Estrangeira - Inglês",
            "Língua Portuguesa e Literatura I",
            "Língua Portuguesa e Literatura II",
            "Língua Portuguesa e Literatura III",
            "Língua Portuguesa e Literatura IV",
            "Linguística I",
            "Linguística III",
            "Linguística IV",
            "Linguística V",
            "Literaturas de Língua Espanhola I",
            "Literaturas de Língua Espanhola II",
            "Literaturas de Língua Espanhola III",
            "Literaturas de Língua Portuguesa II",
            "Literaturas de Língua Portuguesa III",
            "Literaturas de Língua Portuguesa IV",
            "Lógica para Computação",
            "Máquinas Elétricas",
            "Matemática",
            "Matemática Financeira",
            "Matemática I",
            "Matemática II",
            "Matemática III",
            "Matemática IV",
            "Matemática V",
            "Metodologia",
            "Metodologia da Pesquisa",
            "Microcontroladores",
            "Microprocessadores e microcontroladores",
            "Multiletramentos",
            "Música",
            "Natureza e Sociedade",
            "Natureza, Esporte e Lazer",
            "Panorama Historiográfico das Literaturas de Língua Portuguesa",
            "Pesquisa em Lazer",
            "Plantas Medicinais, Aromáticas e Condimentares",
            "Políticas e Legislação Cultural",
            "Políticas Linguísticas",
            "Português e Literatura I",
            "Português e Literatura II",
            "Português e Literatura III",
            "Português e Literatura IV",
            "Prática de ensino em Literatura"
        ]

        for nome in disciplinas