from .base_model import *
from .usuario import *
from .curso import *
from .disciplina import *
from .turma import *
from .registro_atendimento import *
from .evento import *
from .evento_ordinario import *
from .evento_extraordinario import *
from .historico_atendimento import *
