from .base_model import *
from .usuario import *
from .aluno import *
from .servidor import *
from .coordenador import *
from .curso import *
from .disciplina import *
from .turma import *
from .atendimento import *