# Generated by Django 5.0 on 2025-09-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registro', models.CharField(max_length=20, unique=True, verbose_name='Registro')),
                ('tipoPerfil', models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'Professor'), ('ALU', 'Aluno'), ('COOR', 'Coordenador')], max_length=20, verbose_name='Tipo de Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
