# Generated by Django 5.0 on 2025-09-25 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registro', models.CharField(max_length=20, unique=True, verbose_name='Registro')),
                ('tipoPerfil', models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'Professor'), ('ALU', 'Aluno'), ('COOR', 'Coordenador')], max_length=20, verbose_name='Tipo de Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('duracao', models.IntegerField(help_text='Duração', validators=[django.core.validators.MinValueValidator(1)])),
                ('tipocurso', models.CharField(choices=[('SAE', 'superior_agroecologia'), ('SADS', 'superior_ads'), ('SEI', 'superior_eletronica_industrial'), ('SGDL', 'superior_gestao_desportiva_lazer'), ('SLPE', 'superior_letras_port_esp'), ('SPG', 'superior_processos_gerenciais'), ('TCS', 'tecnico_concomitante_subsequente'), ('TI', 'tecnico_integrado'), ('TP', 'tecnico_proeja'), ('TS', 'tecnico_subsequente')], max_length=50)),
                ('coordenador', models.CharField(help_text='Nome do coordenador', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursos', models.CharField(blank=True, max_length=50, null=True)),
                ('professor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do professor (opcional)')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código')),
                ('carga_horaria', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Carga Horária (em horas)')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre da disciplina (1,2,...,10)')),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('periodo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('turno', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='accounts.curso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
