
# Generated by Django 5.2.1 on 2025-09-24 03:20

import django.core.validators
# Generated by Django 5.0 on 2025-09-23 22:38


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursos', models.CharField(blank=True, max_length=50, null=True)),
                ('professor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do professor (opcional)')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código')),
                ('carga_horaria', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Carga Horária (em horas)')),
                ('semestre', models.IntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre da disciplina (1,2,...,10)')),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),

            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registro', models.CharField(max_length=20, unique=True, verbose_name='Registro')),
                ('tipoPerfil', models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'Professor'), ('ALU', 'Aluno'), ('COOR', 'Coordenador')], max_length=20, verbose_name='Tipo de Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
