# Generated by Django 5.2.1 on 2025-09-24 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre da disciplina (1,2,...,10)'),
        ),
    ]
