from .disciplina_view_set import *
# Removed aluno_views_set import
from .evento_view_set import *
from .evento_ordinario_views import *
from .evento_extraordinario_views import *
# Removed coordenador_views_set import
from .curso_views_set import *
# Removed professor_views_set import
from .turma_views_set import *
from .usuario_view_set import *
from .registro_atendimento_views_set import *
from .evento_convocacao_views import *
from .auth_views import *
from .usuario_me_view import * 
from .notificacoes_view import *
from .emails_autorizados_views import *
