from .disciplina_serializer import *
from .turma_serializer import *
from .aluno_serializer import *
from .usuario_serializer import *
from .evento_serializer import *
from .evento_ordinario_serializer import *
from .coordenador_resumido_serializer import *
from .coordenador_serializer import *
from .curso_serializer import *
from .professor_serializer import *
from .curso_coordenador_resumido_serializer import *
from .evento_extraordinario_serializer import *
