from .disciplina_serializer import *
from .turma_serializer import *
from .aluno_serializer import *
from .atendimento_serializer import *
from .coordenador_resumido_serializer import *
from .coordenador_serializer import *
from .curso_serializer import *
from .servidor_serializer import *
from .curso_coordenador_resumido_serializer import *